### ISSUE TITLE
Videotime player not playing vimeo videos

### ISSUE THREAD

**Issue by will-bulluck** [bdecentgmbh/moodle-mod_videotime#49]
We have the 2023011206 version installed and I can not seem to get vimeo videos to play. Any suggestions?

**Comment by stefanscholz** [comment]
Hi @will-bulluck, sorry to hear that you have issues. In order to understand your problem, please provide more details like the moodle version you use, what kind of error message you get (if any), how you have setup the video time activity, which video(s) you tried etc. The more details, the better.

Most common issues are:
- JavaScript issues caused by a corrupt (other) plugin you installed 
- incompatible theme
- using video time on an unsupported version of moodle
- using the wrong Vimeo video url

**Comment by will-bulluck** [comment]
@stefanscholz 

Thanks for the quick reply, We are running this on Totara 12, and this theme we use I have another site running this as well and it works on there. The vimeo link us https://vimeo.com/824066281.

The only option I see maybe being the hang up is that Totara 12 is built off of Moodle 3.3.9

**Comment by stefanscholz** [comment]
Hi @will-bulluck, 

there are distinct versions for moodle and totara. The moodle version does not work in Totara.

If you want to use video time on totara, you can get the appropriate version here: https://bdecent.de/product/video-time/ (select totara as platform) or if you use the totara release (latest totara version is 1.5.5).

Hope this helps!
Stefan

**Comment by will-bulluck** [comment]
@stefanscholz 

So as it turns out, this plugin is the same as what we have installed, Any other tips here?

**Comment by will-bulluck** [comment]
@stefanscholz  just checking in here
